### ISSUE TITLE
Crashing on unseen classes.

### ISSUE THREAD

**Issue by SinghShreyas** [Sanket758/AI-Chatbot-with-Tensorflow#1]
Hi Sanket,

First of all, congratulations on your nice try.

I went through your source code and have some feedback for you.

I have seen your source code and ran it. Your program crashed on the first message that I typed on the terminal as you can see on the attached screenshot. 

![Screenshot 2020-10-13 at 11 54 25 PM](https://user-images.githubusercontent.com/25030681/95863085-7c40ee00-0daf-11eb-980d-a4b364e12f9c.png)

Secondly, you used a neural network for training your model using 200 epochs which I think is not a good way to train your model considering the size of your training data. Your model seems to have an overfitting problem. Your model is not able to generalize on the unseen data. 

Try to go through some conventional machine learning classification algorithms ( I am saying classification algorithms as I can see your model is predicting *tags*) and try to train your model using them.

Anyway, it was a good try. Welcome to the world of AI and machine learning.

Feel free to contact if you have any concern.

Regards,

Shreyas

**Comment by Sanket758** [comment]
First of all i am really glad that you took efforts to go through the code, and thanks for letting us know about this bug, clearly it was a poor programming practice on our side.

![Wont crash now](https://user-images.githubusercontent.com/26123083/96022518-9beb1b80-0e6e-11eb-810f-719dff9dce48.png)

About the model, we have kept it simple so that we can explain it to our teachers. So we haven't done any serious tuning on the model. 
Please understand that this chatbot a very specific to our college, and its only trained on the data related to our college only. So it might not be able to answer all the questions in the world. 

Anyway, thanks for showing the interest. If you have any other improvements please feel free to submit a PR.

**Comment by SinghShreyas** [comment]
Hi,

Hope you are well.

Being a PVPP alumnus it's my pleasure to review the code.

Basically, all the modern chatbots are powered by NLP at its core so that it understands what a user is trying to say.

What you are doing is just classifying your data. So basically what your model is doing currently is taking the user input and giving a prediction which is a line of text from your JSON file. 

Try to implement NLP and other stuff which makes your chatbot intelligent.

I hope it gets integrated into the PVPP website if it becomes intelligent.

Thanks and best wishes for your future.

**Comment by Sanket758** [comment]
Yeah, exactly. 
This concept is called "Retrieval based chatbot", where your chatbot responds through a pre-learned knowledge base. In our case its the JSON file where intents and responses are stored. 
We can definitely crate a more complex chatbot using all the stuff like NLP, you can create a Sequence based model for better result. But thats for future scope.
If you really want to contribute, please feel free to submit a PR.

**Comment by SinghShreyas** [comment]
Definitely, would love to contribute but time is a constraint for me.
Anyways, feel free to contact anytime if you have any new idea.
It was great talking to you.
